# Generated by Django 4.2.3 on 2023-07-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_author_alter_article_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.author"
            ),
        ),
    ]
