# Generated by Django 4.2.3 on 2023-07-15 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
