# Generated by Django 4.2.3 on 2023-07-14 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="academic_title",
        ),
    ]
